"""
项目配置文件
"""

# 模型配置
MODEL_NAME = "Qwen/Qwen3.5-0.8B"

# 数据配置
DATASET_NAME = "gsm8k"
DATASET_CONFIG = "main"  # GSM8K的主配置
MAX_SEQ_LENGTH = 512

# LoRA配置
LORA_R = 16
LORA_ALPHA = 32
LORA_DROPOUT = 0.05
TARGET_MODULES = ["q_proj", "v_proj"]  # 只选q_proj和v_proj节省显存

# SFT训练配置
SFT_OUTPUT_DIR = "./outputs/sft_model"
SFT_NUM_EPOCHS = 1
SFT_BATCH_SIZE = 1
SFT_GRADIENT_ACCUMULATION_STEPS = 8
SFT_LEARNING_RATE = 2e-4
SFT_WARMUP_RATIO = 0.03
SFT_LOGGING_STEPS = 50
SFT_SAVE_STEPS = 500

# DPO训练配置
DPO_OUTPUT_DIR = "./outputs/dpo_model"
DPO_NUM_EPOCHS = 1
DPO_BATCH_SIZE = 1
DPO_GRADIENT_ACCUMULATION_STEPS = 8
DPO_LEARNING_RATE = 5e-5
DPO_BETA = 0.1  # DPO的温度参数
DPO_LOGGING_STEPS = 10
DPO_SAVE_STEPS = 500

# 评估配置
EVAL_BATCH_SIZE = 4
MAX_NEW_TOKENS = 256

# 量化配置（QLoRA）
USE_QLORA = True
LOAD_IN_4BIT = True
BNB_4BIT_COMPUTE_DTYPE = "bfloat16"
BNB_4BIT_USE_DOUBLE_QUANT = True
BNB_4BIT_QUANT_TYPE = "nf4"

# 随机种子
SEED = 42
